`timescale 1ns/1ps
// Reusable SHAKE256 block engine. Byte 0 is din[7:0] / dout[7:0].
// A request is accepted on a rising edge while ready=1. Commands are
// exclusive; init has priority, then absorb, then squeeze.
module shake256_block_engine (
    input  wire          clk,
    input  wire          rst_n,
    input  wire          zeroize,
    input  wire          init,
    input  wire          absorb,
    input  wire          squeeze,
    input  wire          pre_padded,
    input  wire [1087:0] din,
    input  wire [7:0]    valid_bytes,
    input  wire          last,
    output wire [1087:0] dout,
    output wire          ready,
    output reg           done,
    output reg           output_valid,
    output reg           error
);
    localparam IDLE = 3'd0, LAUNCH = 3'd1, WAIT_CORE = 3'd2,
               EXTRA = 3'd3;
`ifdef FMAX_FANOUT
    (* max_fanout = 16 *) reg [2:0] phase;
`else
    reg [2:0] phase;
`endif
    reg [1599:0] sponge;
    reg extra_needed;
    reg finalizing;
    reg finalized;
    wire [1599:0] permutation_out;
    wire permutation_done;
    wire permutation_start = (phase == LAUNCH);
    reg [1087:0] padded;
    integer i;

    always @* begin
        padded = 1088'd0;
        if (last && valid_bytes < 8'd136) begin
            for (i = 0; i < 136; i = i + 1) begin
                if (i < valid_bytes)
                    padded[i*8 +: 8] = din[i*8 +: 8];
                else if (i == valid_bytes)
                    padded[i*8 +: 8] = 8'h1f;
            end
            padded[1087:1080] = padded[1087:1080] ^ 8'h80;
        end else begin
            padded = din;
        end
    end

    keccak_f1600 permutation (
        .clk(clk), .rst_n(rst_n), .zeroize(zeroize),
        .start(permutation_start),
        .state_in(sponge), .state_out(permutation_out),
        .done(permutation_done)
    );

    assign ready = (phase == IDLE);
    assign dout = sponge[1087:0];

    // rst_n is generated by an assert/deassert reset pipeline in the SoC.
    // Keep the large 1600-bit state reset synchronous so reset distribution
    // does not become the Fmax-limiting asynchronous recovery path.
    always @(posedge clk) begin
        if (!rst_n) begin
            phase <= IDLE;
            sponge <= 1600'd0;
            extra_needed <= 1'b0;
            finalizing <= 1'b0;
            finalized <= 1'b0;
            done <= 1'b0;
            output_valid <= 1'b0;
            error <= 1'b0;
        end else if (zeroize) begin
            phase <= IDLE;
            sponge <= 1600'd0;
            extra_needed <= 1'b0;
            finalizing <= 1'b0;
            finalized <= 1'b0;
            done <= 1'b0;
            output_valid <= 1'b0;
            error <= 1'b0;
        end else begin
            done <= 1'b0;
            error <= 1'b0;
            case (phase)
                IDLE: begin
                    if (init) begin
                        sponge <= 1600'd0;
                        extra_needed <= 1'b0;
                        finalizing <= 1'b0;
                        finalized <= 1'b0;
                        output_valid <= 1'b0;
                        done <= 1'b1;
                    end else if (absorb) begin
                        if (finalized || valid_bytes > 8'd136 ||
                            (!last && valid_bytes != 8'd136)) begin
                            error <= 1'b1;
                            done <= 1'b1;
                        end else begin
                            sponge[1087:0] <= sponge[1087:0] ^
                                               (pre_padded ? din : padded);
                            extra_needed <= !pre_padded && last &&
                                            valid_bytes == 8'd136;
                            finalizing <= pre_padded | last;
                            output_valid <= 1'b0;
                            phase <= LAUNCH;
                        end
                    end else if (squeeze) begin
                        if (!finalized) begin
                            error <= 1'b1;
                            done <= 1'b1;
                        end else begin
                            output_valid <= 1'b0;
                            finalizing <= 1'b0;
                            phase <= LAUNCH;
                        end
                    end
                end
                LAUNCH: phase <= WAIT_CORE;
                WAIT_CORE: if (permutation_done) begin
                    sponge <= permutation_out;
                    if (extra_needed) begin
                        phase <= EXTRA;
                        extra_needed <= 1'b0;
                    end else begin
                        phase <= IDLE;
                        done <= 1'b1;
                        if (finalizing) finalized <= 1'b1;
                        if (finalized || finalizing) output_valid <= 1'b1;
                    end
                end
                EXTRA: begin
                    sponge[7:0] <= sponge[7:0] ^ 8'h1f;
                    sponge[1087:1080] <= sponge[1087:1080] ^ 8'h80;
                    phase <= LAUNCH;
                end
                default: phase <= IDLE;
            endcase
        end
    end
endmodule
