"""Reproducible F/H reference vectors generated by Python/OpenSSL SHAKE256.
These do not use the project's C/RTL hash implementation as their oracle.
"""
import hashlib
import random
import sys
from pathlib import Path

rng = random.Random(0x205256)
words = []
for case in range(256):
    mode = case & 1
    if case < 2:
        data = bytes(128)
    elif case < 4:
        data = b'\xff' * 128
    elif case < 36:
        data = bytearray(128)
        data[((case-4)//2)*7] = 1 << (((case-4)//2) % 8)
        data = bytes(data)
    else:
        data = rng.randbytes(128)
    digest = hashlib.shake_256(data[:128 if mode else 96]).digest(32)
    words.append(mode)
    words.extend(int.from_bytes(data[i:i+4], 'little') for i in range(0,128,4))
    words.extend(int.from_bytes(digest[i:i+4], 'little') for i in range(0,32,4))
path = Path(sys.argv[1])
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text(''.join(f'{word:08x}\n' for word in words), encoding='ascii')
print(f'Generated 256 SHAKE256 F/H vectors: {path}')
