# Paths relative to workspace root. Canonical SoC RTL; no board wrapper.
hardware/rtl/cpu/picorv32.v
hardware/rtl/axi/priority_encoder.v
hardware/rtl/axi/arbiter.v
hardware/rtl/axi/axi_crossbar_addr.v
hardware/rtl/axi/axi_crossbar_rd.v
hardware/rtl/axi/axi_crossbar_wr.v
hardware/rtl/axi/axi_crossbar.v
hardware/rtl/axi/axi_register_rd.v
hardware/rtl/axi/axi_register_wr.v
hardware/rtl/axi/axi_interconnect.v
hardware/rtl/axi/axi_ram.v
hardware/rtl/axi/axi_interconnect_2x4_top.v
hardware/rtl/sphincs_shake256/keccak_round.v
hardware/rtl/sphincs_shake256/keccak_f1600.v
hardware/rtl/sphincs_shake256/shake256_block_engine.v
hardware/rtl/sphincs_shake256/spx_thash_shake256_simple_256.v
hardware/rtl/sphincs_shake256/slh_dsa_shake_axi_lite.v
hardware/rtl/iommu/pseudoLRU.sv
hardware/rtl/iommu/dma_iommu_tlb.sv
hardware/rtl/dma/dma_axil_regs.sv
hardware/rtl/dma/dma_access_controller.sv
hardware/rtl/dma/dma_descriptor_fifo.sv
hardware/rtl/dma/dma_completion_fifo.sv
hardware/rtl/dma/dma_axi_scheduler.sv
hardware/rtl/dma/axi_cdma.v
hardware/rtl/dma/axi_dma_rd.v
hardware/rtl/dma/axi_dma_wr.v
hardware/rtl/dma/dma_mmu_axi_top.sv
hardware/rtl/peripherals/soc_uart.v
hardware/rtl/sphincs_shake256/slh_dma_stream_adapter.v
hardware/rtl/peripherals/soc_timer_gpio.v
hardware/rtl/axi/dma_axi_mem_router.v
hardware/rtl/soc/axi_slh_peripherals.v
hardware/rtl/soc/picorv32_slh_soc.v
hardware/rtl/soc/portable_slh_soc_core.v
